### ISSUE TITLE
Can't enable add-on in Blender 3.3.1 LTS.

### ISSUE THREAD

**Issue by HixonECG** [nutti/Screencast-Keys#134]
### System Information
  
* OS: Windows 10
* Blender version: 3.3.1 LTS
* Add-on version: 3.8.0

### Expected behavior

Installing and enabling the addon

### Description about the bug**

I installed the latest, and when I click on the checkbox to enable the addon, I get this error:

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.3.1.0_x64__ppwjx1n5r4v9t\Blender\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\__init__.py", line 153, in register
    register_updater(bl_info)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\screencast_keys\__init__.py", line 100, in register_updater
    updater.init(config)
TypeError: AddonUpdaterManager.init() missing 1 required positional argument: 'config'

```

### Screenshots/Files [Optional]  

![image](https://user-images.githubusercontent.com/116387654/197276635-4f42f7bb-198a-4c80-a1dd-4cb5580d3595.png)

**Comment by JOppelix** [comment]
Hey guys, 
on my system Screencast-Keys run into same issue but different lines of code are claimed.
See following screenshot for details:

<img width="647" alt="2022-10-22-Blender_3_3_1_error_message" src="https://user-images.githubusercontent.com/42702584/197355724-43e0a66f-b8fe-43bf-a628-af84d1e7a4d0.png">

**Comment by JOppelix** [comment]
Hey guys! I got a solution (working in my case)!!

I used manual installation as told in my last description of the issue.
Then I activated the "Enable On Startup" hook, closed Blender and re-opened it.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/42702584/197358491-e3be2232-93c5-47b1-a805-eb0c19f45914.png">


Now the checkbox to activate Screencast Keys was already active after restarting Blender (4) and it can be controlled as desired. Also it works now on my mashine with Blender 3.3.1 (5) !!  See following screenshot with details:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/42702584/197358688-ac44accd-972a-42e6-bcdd-672dbd4456d5.png">

**Comment by JOppelix** [comment]
Short way to solution working with Screencast 3.8 as well:

- Download version 3.8 Zip file from here (found in doc files (docs/installation.md):
https://github.com/nutti/Screencast-Keys/releases/tag/v3.8

- Extract zip file to a temporary location (eg. Downloads or Temp folder)

- Copy or move folder "screencast_keys" from your extracted folder (Screencast-Keys-3.8/src) to the addon folder of Blender   ->  %appdata%/Roaming/Blender Foundation/Blender/3.3/scripts/addons

<img width="986" alt="image" src="https://user-images.githubusercontent.com/42702584/197359635-58d77f23-ceab-45ff-8e12-1662d244a1d7.png">


- Start Blender

- Open menu "Edit" (1) and select "Preferences" (2), search for "screencast" (3) and activate the addon (4).

- Activate the checkbox "Enable On Startup" (5) inside Screencast Keys settings.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/42702584/197359654-2bdad516-a338-4da2-b124-a11ab841fb7f.png">


- Restart Blender

- Screencast Keys (6) is activated an can be controlled (deacted and re-activated) as usual (7).

**Comment by nutti** [comment]
@HixonECG 

Could you reinstall this add-on or try workaround from @JOppelix ?
This issue has already fixed in the latest version (v3.8).

**Comment by HixonECG** [comment]
Apparently... I STUPIDLY installed this using the Microsoft Store, thinking "Oh, it will automatically update Blender for me so I won't forget". But instead, it locks all the files behind impenetrable permissions that I can not override. I have tried using the PowerShell, I tried changing the registry, I tried using the takeown/take ownership command, I tried changing the advanced security user permissions, but nothing works. I am fed up with how Microsoft wants to completely control all aspects of these folders, making it impossible for users to go in and... say... manually install an add-on.
I am going to delete it and install Blender from the website like I should have from the start. I will report back if I can get it to work that way.

**Comment by HixonECG** [comment]
I am happy to report that it does now seem to work! That fixed it. I didn't even need to manually install it, I just needed to NOT use the Microsoft Store version of Blender. So... as far as I can tell, using the Microsoft Store is the worst thing you can do, and there is no way to regain full permissions and control over your files and programs. I deleted it as best as I could from there and reinstalled Blender from their website. Now that I had complete control, everything works just fine.

Except for one thing... when I select "Show Mouse Events" and choose "Event History + Hold Status", and I have select "Show Last Operator" Mode: "Label + ID Name", the hold status doesn't work. It just shows the icon for the mouse as I click the buttons and the event history beneath it, but the mouse click names go away.
![image](https://user-images.githubusercontent.com/116387654/197613589-02e71728-c0e5-4d40-b0de-537095555d45.png)

**Comment by nutti** [comment]
> when I select "Show Mouse Events" and choose "Event History + Hold Status", the mouse click names stop showing up. 

This is same as #131
The unstable version fixes this issue.

**Comment by HixonECG** [comment]
Thanks. I'll look into it. Good work on the add-on!
