### ISSUE TITLE
Doesn't work on macos apple M2  blender 4.1

### ISSUE THREAD

**Issue by westNeighbor** [nutti/Screencast-Keys#200]
### System Information
  
* OS: macos
* Blender version: 4.1
* Add-on version: 3.13

### Description about the bug**

No problem installation, but doesn't show anything, lanuch from terminal and it gives the following errors

`Traceback (most recent call last):
  File "/Users/mhzhao/Library/Application Support/Blender/4.1/scripts/addons/screencast_keys/ops.py", line 1432, in draw_callback
    draw_rect(0, 0, 0, 0, [0.0, 0.0, 0.0, 0.0])
  File "/Users/mhzhao/Library/Application Support/Blender/4.1/scripts/addons/screencast_keys/ops.py", line 282, in draw_rect
    imm.immEnd()
  File "/Users/mhzhao/Library/Application Support/Blender/4.1/scripts/addons/screencast_keys/gpu_utils/imm.py", line 262, in immEnd
    batch = batch_for_shader(shader, 'TRIS', data, indices=indices)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/gpu_extras/batch.py", line 61, in batch_for_shader
    attrs_info = shader.attrs_info_get()
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attrs_info_get'
`

**Comment by nutti** [comment]
It seems the same issue #194 .
Please use the unstable version for now.
https://github.com/nutti/Screencast-Keys/issues/194#issuecomment-1943591734

**Comment by westNeighbor** [comment]
> @westNeighbor
> 
> It seems the same issue #194 . Please use the unstable version for now. [#194 (comment)](https://github.com/nutti/Screencast-Keys/issues/194#issuecomment-1943591734)

Cool, thx.
